import type { Table } from "@tanstack/react-table"
import { ChevronLeft, ChevronRight } from "lucide-react"

import { Button } from "@/shared/components/ui/button"
import { cn } from "@/lib/utils"

export type DataTablePaginationProps<TData> = {
  table: Table<TData>
  className?: string
  navLabel?: string
}

/** Page numbers with gaps as `null` for ellipsis 
 * Generated by AI, to be replaced with a real implementation later.
 * @param current - The current page number
 * @param total - The total number of pages
 * @returns An array of page numbers with gaps as `null` for ellipsis
*/
function paginationItems(current: number, total: number): (number | null)[] {
  if (total <= 7) {
    return Array.from({ length: total }, (_, i) => i + 1)
  }
  const pages = new Set([1, total, current, current - 1, current + 1])
  const sorted = [...pages].filter((p) => p >= 1 && p <= total).sort((a, b) => a - b)
  const out: (number | null)[] = []
  for (let i = 0; i < sorted.length; i++) {
    const n = sorted[i]!
    if (i > 0 && n - sorted[i - 1]! > 1) {
      out.push(null)
    }
    out.push(n)
  }
  return out
}

export function DataTablePagination<TData>({
  table,
  className,
  navLabel = "Table pagination",
}: DataTablePaginationProps<TData>) {
  const totalRows = table.getRowCount()
  const { pageIndex, pageSize } = table.getState().pagination
  const pageCount = table.getPageCount()
  const totalPages = Math.max(1, pageCount)

  const currentPage = pageIndex + 1

  const rangeStart =
    totalRows === 0 ? 0 : pageIndex * pageSize + 1
  const rangeEnd =
    totalRows === 0 ? 0 : Math.min((pageIndex + 1) * pageSize, totalRows)

  const pageButtons = paginationItems(currentPage, totalPages)

  return (
    <div
      className={cn(
        "flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between",
        className
      )}
    >
      <p className="font-semibold text-accent-foreground text-xs tabular-nums">
        {totalRows === 0 ? (
          "No results"
        ) : (
          <>
            Showing{" "}
            <span>{rangeStart}</span>–
            <span>{rangeEnd}</span> of{" "}
            <span>{totalRows}</span>
          </>
        )}
      </p>

      {totalRows > 0 ? (
        <nav
          className="flex flex-wrap items-center justify-end gap-2"
          aria-label={navLabel}
        >
          <Button
            type="button"
            variant="outline"
            size="sm"
            className="size-8 xl:size-10"
            disabled={currentPage <= 1}
            onClick={() => table.setPageIndex(Math.max(0, pageIndex - 1))}
            aria-label="Previous page"
          >
            <ChevronLeft className="size-4" />
          </Button>

          <ul className="flex items-center gap-1">
            {pageButtons.map((item, i) =>
              item === null ? (
                <li
                  key={`ellipsis-${i}`}
                  className="text-muted-foreground flex size-8 items-center justify-center text-sm"
                  aria-hidden
                >
                  …
                </li>
              ) : (
                <li key={item}>
                  <Button
                    type="button"
                    variant={item === currentPage ? "secondary" : "ghost"}
                    size="icon-sm"
                    className={cn(
                      "size-8 xl:size-10 bg-border",
                      item === currentPage && "bg-primary/10 border-primary border"
                    )}
                    aria-label={`Page ${item}`}
                    aria-current={item === currentPage ? "page" : undefined}
                    onClick={() => table.setPageIndex(item - 1)}
                  >
                    {item}
                  </Button>
                </li>
              )
            )}
          </ul>

          <Button
            type="button"
            variant="outline"
            size="sm"
            className="size-8 xl:size-10"
            disabled={currentPage >= totalPages}
            onClick={() =>
              table.setPageIndex(Math.min(totalPages - 1, pageIndex + 1))
            }
            aria-label="Next page"
          >
            <ChevronRight className="size-4" />
          </Button>
        </nav>
      ) : null}
    </div>
  )
}
