/**
 * Generated by AI, to be replaced with a real API call later.
 * Mock server-side list filtering and sorting for settings groups list.
 */
import { mockGroupData } from "../mock/settingsListData"
import type { SettingsGroupRow } from "../types/settingsList"

export type SettingsGroupQuery = {
  search: string
  statusFilter: string
  pageIndex: number
  pageSize: number
  sortBy: string
}

export type SettingsGroupPageResult = {
  rows: SettingsGroupRow[]
  totalCount: number
}

function filterSettingsGroup(
  rows: readonly SettingsGroupRow[],
  search: string
): SettingsGroupRow[] {
  const q = search.trim().toLowerCase()
  if (!q) return [...rows]

  return rows.filter((row) => {
    const inName = row.name.toLowerCase().includes(q)
    const inDescription = row.description?.toLowerCase().includes(q)
    return inName || inDescription
  })
}

function sortSettingsGroup(
  rows: SettingsGroupRow[],
  sortBy: string
): SettingsGroupRow[] {
  const sorted = [...rows]

  switch (sortBy) {
    case "name_asc":
      return sorted.sort((a, b) => a.name.localeCompare(b.name))

    case "name_desc":
      return sorted.sort((a, b) => b.name.localeCompare(a.name))

    case "created_asc":
      return sorted.sort(
        (a, b) =>
          new Date(a.lastUpdated.date).getTime() -
          new Date(b.lastUpdated.date).getTime()
      )

    case "created_desc":
    case "":
    case "all":
    default:
      return sorted.sort(
        (a, b) =>
          new Date(b.lastUpdated.date).getTime() -
          new Date(a.lastUpdated.date).getTime()
      )
  }
}

/**
 * Mock “server” list: filter → sort → paginate over {@link mockGroupData}.
 * Matches layout fields from image_ff5b0a.png.
 */
export function querySettingsPage(
  query: SettingsGroupQuery
): SettingsGroupPageResult {
  // Filter
  const filtered = filterSettingsGroup(mockGroupData, query.search)

  // Sort
  const sorted = sortSettingsGroup(filtered, query.sortBy)

  // Paginate
  const totalCount = sorted.length
  const start = query.pageIndex * query.pageSize
  const rows = sorted.slice(start, start + query.pageSize)

  return { rows, totalCount }
}