/**
 * Generated by AI, to be replaced with a real API call later.
 * Mock server-side list filtering and sorting for settings groups list.
 */
import type { SortingState } from "@tanstack/react-table"
import { mockGroupData } from "../mock/settingsListData"
import type { SettingsGroupRow } from "../types/settingsList"

export type SettingsGroupQuery = {
  search: string
  statusFilter: string
  typeFilter: string
  pageIndex: number
  pageSize: number
  sorting: SortingState
}

export type SettingsGroupPageResult = {
  rows: SettingsGroupRow[]
  totalCount: number
}

function filterSettingsGroup(
  rows: readonly SettingsGroupRow[],
  search: string
): SettingsGroupRow[] {
  const q = search.trim().toLowerCase()
  if (!q) return [...rows]

  return rows.filter((row) => {
    const inName = row.name.toLowerCase().includes(q)
    const inDescription = row.description?.toLowerCase().includes(q)
    return inName || inDescription
  })
}

function sortSettingsGroup(
  rows: SettingsGroupRow[],
  sorting: SortingState
): SettingsGroupRow[] {
  if (!sorting || sorting.length === 0) return rows

  const [{ id, desc }] = sorting

  return [...rows].sort((a, b) => {
    let valueA: any = a[id as keyof SettingsGroupRow]
    let valueB: any = b[id as keyof SettingsGroupRow]

    // Handle nested objects if sorting by last updated details
    if (id === "lastUpdated") {
      valueA = new Date(a.lastUpdated.date).getTime()
      valueB = new Date(b.lastUpdated.date).getTime()
    }

    if (valueA < valueB) return desc ? 1 : -1
    if (valueA > valueB) return desc ? -1 : 1
    return 0
  })
}

/**
 * Mock “server” list: filter → sort → paginate over {@link mockGroupData}.
 * Matches layout fields from image_ff5b0a.png.
 */
export function querySettingsPage(query: SettingsGroupQuery): SettingsGroupPageResult {
  // 1. Filter
  const filtered = filterSettingsGroup(mockGroupData, query.search)

  // 2. Sort
  const sorted = sortSettingsGroup(filtered, query.sorting)

  // 3. Paginate
  const totalCount = sorted.length
  const start = query.pageIndex * query.pageSize
  const rows = sorted.slice(start, start + query.pageSize)

  return { rows, totalCount }
}