import type { Cabinet } from "../types/cabinetList"

/**
 * Mock data for cabinets list.
 * Generated by AI, to be replaced with a real API call later.
 */
export const mockCabinetsList: Cabinet[] = [
  {
    id: "C0000001",
    name: "Cabinet 001",
    city: "Amsterdam",
    zipCode: "1061 AZ",
    street: "Jan van Galenstraat",
    number: "1390",
    latitude: 52.3768,
    longitude: 4.8462,
    status: "warning",
    serialNumber: "132434323432432434",
    accessType: "",
    country: "",
    addressLine2: "",
    lockCode: "",
    assignedAt: "",
    createdAt: "",
    description: "",
    smart: true,
    tenantId: "",
    deviceState: {
      assetPresent: false,
      assetStateChangedAt: "",
      createdAt: "",
      deviceInstallationId: "",
      doorOpen: false,
      doorStateChangedAt: "",
      lastSeenAt: "",
      rssi: 0,
      temperature: 20,
      assetHealth: ""
    }
  },
  {
    id: "C0000002",
    name: "Cabinet 002",
    city: "Groningen",
    zipCode: "1072 LR",
    street: "Ferdinand Bolstraat",
    number: "112",
    latitude: 52.3537,
    longitude: 4.8912,
    status: "urgent",
    serialNumber: "132434323432432434",
    accessType: "",
    country: "",
    addressLine2: "",
    lockCode: "",
    assignedAt: "",
    createdAt: "",
    description: "",
    smart: true,
    tenantId: "",
    deviceState: {
      assetPresent: false,
      assetStateChangedAt: "",
      createdAt: "",
      deviceInstallationId: "",
      doorOpen: false,
      doorStateChangedAt: "",
      lastSeenAt: "",
      rssi: 0,
      temperature: 22,
      assetHealth: ""
    }
  }
];