import type { CabinetActivityRow } from "../types/activityList";

/**
 * Mock data for cabinets list.
 * Generated by AI, to be replaced with a real API call later.
 */
// export const mockCabinetActivities: CabinetActivityRow[] = [
//   {
//     id: "act-001",
//     time: "May 26, 13:38",
//     activity: "General Maintenance",
//     cabinetName: "CAB - 102",
//     category: "Hardware",
//     notes: "Door closed again",
//     group: "",
//     addedBy: "Wilson Stanton"
//     addedBy: "Wilson Stanton"
//   },
//   {
//     id: "act-002",
//     time: "May 26, 13:21",
//     activity: "Check-up",
//     cabinetName: "CAB - 078",
//     category: "Network",
//     notes: "Awaiting connection recovery",
//     group: "",
//     addedBy: "Wilson Stanton"
//     addedBy: "Wilson Stanton"
//   },
//   {
//     id: "act-003",
//     time: "May 26, 12:54",
//     activity: "Battery Replaced",
//     cabinetName: "CAB - 045",
//     category: "Security",
//     notes: "Asset placed back",
//     group: "",
//     addedBy: "Wilson Stanton"
//     addedBy: "Wilson Stanton"
//   },
//   {
//     id: "act-004",
//     time: "May 26, 12:51",
//     activity: "Pads Replaced",
//     temperature: "55",
//     cabinetName: "CAB - 019",
//     category: "Environment",
//     notes: "Temp. back to normal",
//     group: "",
//     addedBy: "Wilson Stanton"
//     addedBy: "Wilson Stanton"
//   },
//   {
//     id: "act-005",
//     time: "May 26, 12:30",
//     activity: "Data Retrieved",
//     temperature: "-5",
//     cabinetName: "CAB - 079",
//     category: "Environment",
//     notes: "Investigating HVAC settings",
//     group: "",
//     addedBy: "Wilson Stanton"
//     addedBy: "Wilson Stanton"
//   },
//   {
//     id: "act-006",
//     time: "May 26, 12:23",
//     activity: "Battery Replaced",
//     cabinetName: "CAB - 031",
//     category: "Hardware",
//     notes: "Fan unit replacement scheduled",
//     group: "",
//     addedBy: "Wilson Stanton"
//     addedBy: "Wilson Stanton"
//   },
//   {
//     id: "act-007",
//     time: "May 26, 12:08",
//     activity: "Pads Replaced",
//     temperature: "-5",
//     cabinetName: "CAB - 085",
//     category: "Environment",
//     notes: "Temp. back to normal",
//     group: "",
//     addedBy: "Wilson Stanton"
//     addedBy: "Wilson Stanton"
//   },
// ];
export const mockCabinetIncidents: CabinetActivityRow[] = [
  {
    id: "act-001",
    time: "May 26, 13:38",
    activity: "Door open for >15 minutes",
    cabinetName: "CAB - 102",
    category: "Hardware",
    notes: "Door closed again",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-002",
    time: "May 26, 13:21",
    activity: "Connectivity lost",
    cabinetName: "CAB - 078",
    category: "Network",
    notes: "Awaiting connection recovery",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-003",
    time: "May 26, 12:54",
    activity: "Asset removed",
    cabinetName: "CAB - 045",
    category: "Security",
    notes: "Asset placed back",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-004",
    time: "May 26, 12:51",
    activity: "Temperature too high",
    temperature: "55",
    cabinetName: "CAB - 019",
    category: "Environment",
    notes: "Temp. back to normal",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-005",
    time: "May 26, 12:30",
    activity: "Temperature too low",
    temperature: "-5",
    cabinetName: "CAB - 079",
    category: "Environment",
    notes: "Investigating HVAC settings",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-006",
    time: "May 26, 12:23",
    activity: "Ventilator error",
    cabinetName: "CAB - 031",
    category: "Hardware",
    notes: "Fan unit replacement scheduled",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-007",
    time: "May 26, 12:08",
    activity: "Temperature too low",
    temperature: "-5",
    cabinetName: "CAB - 085",
    category: "Environment",
    notes: "Temp. back to normal",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-008",
    time: "May 26, 11:47",
    activity: "Connectivity lost",
    cabinetName: "CAB - 091",
    category: "Network",
    notes: "Connectivity restored",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-009",
    time: "May 26, 11:25",
    activity: "Asset removed",
    cabinetName: "CAB - 035",
    category: "Security",
    notes: "Asset placed back",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-010",
    time: "May 26, 11:19",
    activity: "Pads replaced",
    cabinetName: "CAB - 123",
    category: "Maintenance",
    notes: "Replaced by Skylar Franci",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-011",
    time: "May 26, 11:05",
    activity: "Data retrieved",
    cabinetName: "CAB - 109",
    category: "Maintenance",
    notes: "Retrieved by Brandon Kenter",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-012",
    time: "May 26, 11:01",
    activity: "Battery replaced",
    cabinetName: "CAB - 081",
    category: "Maintenance",
    notes: "Replaced by Wilson Stanton",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0002",
    time: "May 26, 13:21",
    activity: "Connectivity lost",
    cabinetName: "CAB - 078",
    category: "Network",
    notes: "Awaiting connection recovery",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0003",
    time: "May 26, 12:54",
    activity: "Asset removed",
    cabinetName: "CAB - 045",
    category: "Security",
    notes: "Asset placed back",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0004",
    time: "May 26, 12:51",
    activity: "Temperature too high",
    temperature: "55",
    cabinetName: "CAB - 019",
    category: "Environment",
    notes: "Temp. back to normal",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0005",
    time: "May 26, 12:30",
    activity: "Temperature too low",
    temperature: "-55",
    cabinetName: "CAB - 079",
    category: "Environment",
    notes: "Investigating HVAC settings",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0006",
    time: "May 26, 12:23",
    activity: "Ventilator error",
    cabinetName: "CAB - 031",
    category: "Hardware",
    notes: "Fan unit replacement scheduled",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0007",
    time: "May 26, 12:08",
    activity: "Temperature too low",
    temperature: "-55",
    cabinetName: "CAB - 085",
    category: "Environment",
    notes: "Temp. back to normal",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0008",
    time: "May 26, 11:47",
    activity: "Connectivity lost",
    cabinetName: "CAB - 091",
    category: "Network",
    notes: "Connectivity restored",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0009",
    time: "May 26, 11:25",
    activity: "Asset removed",
    cabinetName: "CAB - 035",
    category: "Security",
    notes: "Asset placed back",
    group: "May 26"
  },
  {
    id: "act-0100",
    time: "May 26, 11:19",
    activity: "Pads replaced",
    cabinetName: "CAB - 123",
    category: "Maintenance",
    notes: "Replaced by Skylar Franci",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0101",
    time: "May 26, 11:05",
    activity: "Data retrieved",
    cabinetName: "CAB - 109",
    category: "Maintenance",
    notes: "Retrieved by Brandon Kenter",
    group: "",
    addedBy: "Wilson Stanton"
  },
  {
    id: "act-0102",
    time: "May 26, 11:01",
    activity: "Battery replaced",
    cabinetName: "CAB - 081",
    category: "Maintenance",
    notes: "Replaced by Wilson Stanton",
    group: "",
    addedBy: "Wilson Stanton"
  },
];