/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { cn, formatISODate } from "@/lib/utils"
import type { CabinetListRow } from "../types/cabinetList"
import {
  cabinetStatusBadgeClass,
  statusBadgeColor
} from "../lib/cabinetListDisplay"
import { CabinetRowActions } from "./CabinetRowActions"

const columnHelper = createColumnHelper<CabinetListRow>()

export const cabinetListColumns = [
  columnHelper.accessor("name", {
    id: "cabinet",
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Cabinet Name" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => (
      <div className="flex min-w-0 flex-col gap-0.5">
        <span className="truncate font-medium">{row.original.name}</span>
      </div>
    ),
  }),
  columnHelper.accessor("city", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="City" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => row.original.city
  }),
  columnHelper.accessor("zip", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Zip Code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "tabular-nums",
    },
    cell: ({ row }) => row.original.zip
  }),
  columnHelper.accessor("street", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Street" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "tabular-nums",
    },
    cell: ({ row }) => row.original.street
  }),
  columnHelper.accessor("hNo", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="h. No." />
    ),
    meta: {
      headerClassName: "",
      cellClassName:
        "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => formatISODate(row.original.hNo),
  }),
  columnHelper.accessor("lastActivityAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Last Update" />
    ),
    meta: {
      headerClassName: "",
      cellClassName:
        "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => formatISODate(row.original.lastActivityAt),
  }),
  columnHelper.accessor("cabinetCode", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Cabinet Code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName:
        "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.cabinetCode,
  }),
  columnHelper.accessor("updaidCode", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Updaid Code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName:
        "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.updaidCode,
  }),
  columnHelper.accessor("status", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Status" />
    ),
    meta: {
      headerClassName: "w-[10%]",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => (
      <span
        className={cn("flex items-center capitalize gap-1")}
      >
        <span className={cn("size-1 block rounded-full",cabinetStatusBadgeClass(row.original.status))}></span>
        <span className={cn(statusBadgeColor(row.original.status))}>{row.original.status}</span>
      </span>
    ),
  }),
  columnHelper.display({
    id: "actions",
    header: "Actions",
    enableSorting: false,
    meta: {
      headerClassName: "text-center",
      cellClassName: "",
    },
    cell: ({ row }) => <CabinetRowActions row={row.original} />,
  }),
]
