/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { cn, formatISODate } from "@/lib/utils"
import {
  cabinetStatusBadgeClass,
  cabinetStatusLabel,
  statusBadgeColor
} from "../lib/cabinetListDisplay"
import { CabinetRowActions } from "./CabinetRowActions"
import { Link } from "react-router"
import type { Cabinet } from "../types/cabinetList"

const columnHelper = createColumnHelper<Cabinet>()

export const cabinetListColumns = (canManageCabinets: boolean) => [
  columnHelper.accessor("name", {
    id: "cabinet",
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Cabinet Name" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => (
      <div className="flex min-w-0 flex-col gap-0.5">
        <Link to={`/cabinets/list/${row.original.id}`} className="truncate font-medium underline">{row.original.name}</Link>
      </div>
    ),
  }),
  columnHelper.accessor("city", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="City" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => row.original.city
  }),
  columnHelper.accessor("zipCode", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Zip Code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "tabular-nums",
    },
    cell: ({ row }) => row.original.zipCode
  }),
  columnHelper.accessor("addressLine1", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Street" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "tabular-nums",
    },
    cell: ({ row }) => row.original.addressLine1
  }),
  columnHelper.accessor("houseNumber", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Number" />
    ),
    meta: {
      headerClassName: "",
      cellClassName:
        "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.houseNumber,
  }),
  columnHelper.accessor("lastActivityAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Last Update" />
    ),
    meta: {
      headerClassName: "",
      cellClassName:
        "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => formatISODate(row.original.lastActivityAt),
  }),
  // columnHelper.accessor("cabinetCode", {
  //   header: ({ column }) => (
  //     <DataTableColumnHeader column={column} title="Cabinet Code" />
  //   ),
  //   meta: {
  //     headerClassName: "",
  //     cellClassName:
  //       "align-middle whitespace-nowrap",
  //   },
  //   cell: ({ row }) => row.original.cabinetCode,
  // }),
  // columnHelper.accessor("updaidCode", {
  //   header: ({ column }) => (
  //     <DataTableColumnHeader column={column} title="Updaid Code" />
  //   ),
  //   meta: {
  //     headerClassName: "",
  //     cellClassName:
  //       "align-middle whitespace-nowrap",
  //   },
  //   cell: ({ row }) => row.original.updaidCode,
  // }),
  columnHelper.accessor("status", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Status" />
    ),
    meta: {
      headerClassName: "w-[10%]",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => (
      <span
        className={cn("flex items-center capitalize gap-1")}
      >
        <span className={cn("size-1 block rounded-full", cabinetStatusBadgeClass(row.original.status))}></span>
        <span className={cn(statusBadgeColor(row.original.status))}>{cabinetStatusLabel(row.original.status)}</span>
      </span>
    ),
  }),
  ...(canManageCabinets
    ? [
      columnHelper.display({
        id: "actions",
        header: "Actions",
        enableSorting: false,
        meta: {
          headerClassName: "text-center",
          cellClassName: "",
        },
        cell: ({ row }) => <CabinetRowActions row={row.original} />,
      }),
      ]
    : []),
]
