/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { Badge } from "@/shared/components/ui/badge"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { cn, formatISODate } from "@/lib/utils"
import type { CabinetListRow } from "../types/cabinetList"
import {
  cabinetStatusBadgeClass,
  cabinetStatusLabel,
  cabinetTypeLabel
} from "../lib/cabinetListDisplay"
import { CabinetRowActions } from "./CabinetRowActions"

const columnHelper = createColumnHelper<CabinetListRow>()

export const cabinetListColumns = [
  columnHelper.accessor("name", {
    id: "cabinet",
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Cabinet" />
    ),
    meta: {
      headerClassName: "w-[16%] pl-4",
      cellClassName: "pl-4 align-middle",
    },
    cell: ({ row }) => (
      <div className="flex min-w-0 flex-col gap-0.5">
        <span className="truncate font-medium">{row.original.name}</span>
        <span className="text-muted-foreground truncate text-xs tabular-nums">
          {row.original.serial}
        </span>
      </div>
    ),
  }),
  columnHelper.accessor("status", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Status" />
    ),
    meta: {
      headerClassName: "w-[10%]",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => (
      <Badge
        variant="outline"
        className={cn("font-medium capitalize", cabinetStatusBadgeClass(row.original.status))}
      >
        {cabinetStatusLabel(row.original.status)}
      </Badge>
    ),
  }),
  columnHelper.accessor("type", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Type" />
    ),
    meta: {
      headerClassName: "w-[12%]",
      cellClassName: "text-foreground align-middle text-sm",
    },
    cell: ({ row }) => cabinetTypeLabel(row.original.type),
  }),
  columnHelper.accessor("location", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Location" />
    ),
    meta: {
      headerClassName: "w-[22%]",
      cellClassName:
        "text-muted-foreground align-middle text-sm leading-snug wrap-break-word whitespace-normal",
    },
  }),
  columnHelper.accessor("asset", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Asset" />
    ),
    meta: {
      headerClassName: "w-[8%]",
      cellClassName: "align-middle text-sm",
    },
    cell: ({ row }) =>
      row.original.asset === "aed" ? (
        <span className="font-medium">AED</span>
      ) : (
        <span className="text-muted-foreground">None</span>
      ),
  }),
  columnHelper.accessor("temperatureC", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Temperature" />
    ),
    meta: {
      headerClassName: "w-[10%]",
      cellClassName: "text-muted-foreground align-middle text-sm tabular-nums",
    },
    cell: ({ row }) =>
      row.original.temperatureC != null
        ? `${row.original.temperatureC.toFixed(1)} °C`
        : "—",
  }),
  columnHelper.accessor("lastActivityAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Last activity" />
    ),
    meta: {
      headerClassName: "w-[14%]",
      cellClassName:
        "text-muted-foreground align-middle text-sm tabular-nums whitespace-nowrap",
    },
    cell: ({ row }) => formatISODate(row.original.lastActivityAt),
  }),
  columnHelper.display({
    id: "actions",
    header: "Actions",
    enableSorting: false,
    meta: {
      headerClassName: "w-[8%] pr-4 text-right",
      cellClassName: "pr-4 text-right align-middle",
    },
    cell: ({ row }) => <CabinetRowActions row={row.original} />,
  }),
]
