/**
 * Generated by AI, to be replaced with a real API call later.
 * Mock server-side list filtering and sorting for cabinets list.
 */
import type { SortingState } from "@tanstack/react-table"
import type { CabinetListRow } from "../types/cabinetList"
import { mockCabinetsList } from "../mock/mockCabinetsList"

const STATUS_FILTER_ALL = "all"
const TYPE_FILTER_ALL = "all"

export type CabinetsListQuery = {
  search: string
  statusFilter: string
  typeFilter: string
  pageIndex: number
  pageSize: number
  sorting: SortingState
}

export type CabinetsListPageResult = {
  rows: CabinetListRow[]
  totalCount: number
}

function filterCabinets(
  rows: readonly CabinetListRow[],
  search: string,
  statusFilter: string,
  typeFilter: string
): CabinetListRow[] {
  const q = search.trim().toLowerCase()
  return rows.filter((row) => {
    if (statusFilter !== STATUS_FILTER_ALL && row.status !== statusFilter) {
      return false
    }
    if (typeFilter !== TYPE_FILTER_ALL && row.type !== typeFilter) {
      return false
    }
    if (q) {
      const inName = row.name.toLowerCase().includes(q)
      const inSerial = row.serial.toLowerCase().includes(q)
      if (!inName && !inSerial) return false
    }
    return true
  })
}

function compareRows(a: CabinetListRow, b: CabinetListRow, columnId: string): number {
  switch (columnId) {
    case "cabinet":
      return (
        a.name.localeCompare(b.name, undefined, { sensitivity: "base" })
      )
    case "status":
      return a.status.localeCompare(b.status)
    case "type":
      return a.type.localeCompare(b.type)
    case "location":
      return a.location.localeCompare(b.location, undefined, { sensitivity: "base" })
    case "asset":
      return a.asset.localeCompare(b.asset)
    case "temperatureC": {
      if (a.temperatureC == null && b.temperatureC == null) return 0
      if (a.temperatureC == null) return 1
      if (b.temperatureC == null) return -1
      return a.temperatureC - b.temperatureC
    }
    case "lastActivityAt":
      return a.lastActivityAt.localeCompare(b.lastActivityAt)
    default:
      return 0
  }
}

/**
 * Mock “server” list: filter → sort → paginate over {@link mockCabinetsList}.
 * Replace with a real `fetch()` when an API exists; keep the same result shape.
 */
export function queryCabinetsListPage(query: CabinetsListQuery): CabinetsListPageResult {
  const filtered = filterCabinets(
    mockCabinetsList,
    query.search,
    query.statusFilter,
    query.typeFilter
  )

  const sorted = [...filtered]
  const sort = query.sorting[0]
  if (sort) {
    sorted.sort((a, b) => {
      const cmp = compareRows(a, b, sort.id)
      return sort.desc ? -cmp : cmp
    })
  }

  const totalCount = sorted.length
  const start = query.pageIndex * query.pageSize
  const rows = sorted.slice(start, start + query.pageSize)

  return { rows, totalCount }
}
