/**
 * Generated by AI, to be replaced with a real API call later.
 * Mock server-side list filtering and sorting for cabinets list.
 */
import type { SortingState } from "@tanstack/react-table"
import type { Cabinet } from "../types/cabinetList"
import { mockCabinetsList } from "../mock/mockCabinetsList"

const STATUS_FILTER_ALL = "all"
const CITY_FILTER_ALL = "all"

export type CabinetsListQuery = {
  search: string
  statusFilter: string
  pageIndex: number
  pageSize: number
  sorting: SortingState
  city: string
  data: Cabinet[]
}

export type CabinetsListPageResult = {
  rows: Cabinet[]
  totalCount: number
}

export function filterCabinets(
  rows: readonly Cabinet[],
  search: string,
  statusFilter: string,
  city: string,
): Cabinet[] {
  const q = search.trim().toLowerCase()
  return rows.filter((row) => {
    if (statusFilter !== STATUS_FILTER_ALL && row.status !== statusFilter) {
      return false
    }
    if (city !== CITY_FILTER_ALL && row.city !== city) {
      return false
    }
    if (q) {
      const inName = row.name.toLowerCase().includes(q)
      const inCity = row.city.toLowerCase().includes(q)
      const inZipCode = row.zipCode?.toLowerCase().includes(q)
      const inSerial = row?.serialNumber?.toLowerCase().includes(q)
      const inStreet = row?.street?.toLowerCase().includes(q)
      const inNumber = row?.number?.toLowerCase().includes(q)
      const status = row?.status?.toLowerCase().includes(q)
      if (!inName && !inCity && !inZipCode && !inSerial && !inStreet && !inNumber && !status) return false
    }
    return true
  })
}

function compareRows(a: Cabinet, b: Cabinet, columnId: string): number {
  switch (columnId) {
    case "cabinet":
      return (
        a.name.localeCompare(b.name, undefined, { sensitivity: "base" })
      )
    case "status":
      return a.status.localeCompare(b.status)
    case "city":
      return a.city.localeCompare(b.city, undefined, { sensitivity: "base" })
    case "zipCode":
      return a.zipCode?.localeCompare(b.zipCode, undefined, { sensitivity: "base" }) || 0
    case "street":
      return a.street?.localeCompare(b.street, undefined, { sensitivity: "base" }) || 0
    case "number":
      return a.number?.localeCompare(b.number, undefined, { sensitivity: "base" }) || 0
    case "createdAt":
      return a.createdAt?.localeCompare(b.createdAt, undefined, { sensitivity: "base" }) || 0
    default:
      return 0
  }
}

/**
 * Mock “server” list: filter → sort → paginate over {@link mockCabinetsList}.
 * Replace with a real `fetch()` when an API exists; keep the same result shape.
 */
export function queryCabinetsListPage(query: CabinetsListQuery): CabinetsListPageResult {
  const filtered = filterCabinets(
    query.data,
    query.search,
    query.statusFilter,
    query.city
  )

  const sorted = [...filtered]
  const sort = query.sorting[0]
  if (sort) {
    sorted.sort((a, b) => {
      const cmp = compareRows(a, b, sort.id)
      return sort.desc ? -cmp : cmp
    })
  }

  const totalCount = sorted.length
  const start = query.pageIndex * query.pageSize
  const rows = sorted.slice(start, start + query.pageSize)

  return { rows, totalCount }
}
