/**
 * Generated by AI, to be replaced with a real API call later.
 * Mock server-side list filtering and sorting for cabinets list.
 */
import type { SortingState } from "@tanstack/react-table"
import type { FactoryRow } from "../types/factoryType"
import { mockFactoryList } from "../mock/mockFactoryStats"

export type FactoryOverviewQuery = {
  search: string
  pageIndex: number
  pageSize: number
  sorting: SortingState
  prefix: string
  linked: string
}

export type CabinetsListPageResult = {
  rows: FactoryRow[]
  totalCount: number
}

function filterFactoryRows(
  rows: readonly FactoryRow[],
  search: string
): FactoryRow[] {
  const q = search.trim().toLowerCase()

  if (!q) return [...rows]

  return rows.filter((row) => {
    return (
      row.id.toLowerCase().includes(q) ||
      row.serial.toLowerCase().includes(q) ||
      row.imei.toLowerCase().includes(q)
    )
  })
}

function compareRows(
  a: FactoryRow,
  b: FactoryRow,
  columnId: string
): number {
  switch (columnId) {
    case "id":
      return a.id.localeCompare(b.id)

    case "serial":
      return a.serial.localeCompare(b.serial)

    case "imei":
      return a.imei.localeCompare(b.imei)

    case "prefix":
      return a.prefix.localeCompare(b.prefix)

    case "linkedOn":
      return (
        new Date(a.linkedOn).getTime() -
        new Date(b.linkedOn).getTime()
      )

    case "generatedOn":
      return (
        new Date(a.generatedOn).getTime() -
        new Date(b.generatedOn).getTime()
      )

    case "status":
      return a.status.localeCompare(b.status)

    default:
      return 0
  }
}
/**
 * Mock “server” list: filter → sort → paginate over {@link mockFactoryList}.
 * Replace with a real `fetch()` when an API exists; keep the same result shape.
 */
export function queryFactoryOverviewPage(query: FactoryOverviewQuery): CabinetsListPageResult {
  const filtered = filterFactoryRows(
    mockFactoryList,
    query.search,
  )

  const sorted = [...filtered]
  const sort = query.sorting[0]
  if (sort) {
    sorted.sort((a, b) => {
      const cmp = compareRows(a, b, sort.id)
      return sort.desc ? -cmp : cmp
    })
  }

  const totalCount = sorted.length
  const start = query.pageIndex * query.pageSize
  const rows = sorted.slice(start, start + query.pageSize)

  return { rows, totalCount }
}
