/**
 * Generated by AI, to be replaced with a real API call later.
 * Mock server-side list filtering and sorting for cabinets list.
 */
import type { SortingState } from "@tanstack/react-table"
import type { FactoryRow } from "../types/factoryType"
import type { DateRange } from "react-day-picker"

export type FactoryOverviewQuery = {
  search: string
  pageIndex: number
  pageSize: number
  sorting: SortingState
  prefix: string
  linked: string
  data: FactoryRow[]
  dateRange: DateRange | null
}

export type CabinetsListPageResult = {
  rows: FactoryRow[]
  totalCount: number
}
// const matchesDate = (() => {
//   const createdAt = new Date(row.createdAt)

//   if (dateRange?.from && createdAt < dateRange.from) {
//     return false
//   }

//   if (dateRange?.to) {
//     const endDate = new Date(dateRange.to)
//     endDate.setHours(23, 59, 59, 999)

//     if (createdAt > endDate) {
//       return false
//     }
//   }

//   return true
// })()

function filterFactoryRows(
  rows: readonly FactoryRow[],
  search: string,
  prefix: string,
  linked: string,
  dateRange: DateRange | null
): FactoryRow[] {
  const q = search.trim().toLowerCase()

  return rows.filter((row) => {
    const matchesSearch =
      !q ||
      row.id.toLowerCase().includes(q) ||
      row.imei?.toLowerCase().includes(q) ||
      row.serialNumber.toLowerCase().includes(q)

    const matchesPrefix =
      !prefix ||
      prefix === "all" ||
      row.prefix === prefix

    const matchesLinked =
      linked === "all" ||
      (linked === "linked" && row.deviceLinked) ||
      (linked === "unlinked" && !row.deviceLinked)

    const createdAt = new Date(row.createdAt)

    const matchesDate =
      (!dateRange?.from || createdAt >= dateRange.from) &&
      (!dateRange?.to || createdAt <= dateRange.to)

    return (
      matchesSearch 
      &&
      matchesPrefix 
      &&
      matchesLinked 
      &&
      matchesDate
    )
  })
}

function compareRows(
  a: FactoryRow,
  b: FactoryRow,
  columnId: string
): number {
  switch (columnId) {
    case "id":
      return a.id.localeCompare(b.id)

    case "serialNumber":
      return a.serialNumber.localeCompare(b.serialNumber)

    case "createdAt":
      return (
        new Date(a.createdAt).getTime() -
        new Date(b.createdAt).getTime()
      )

    case "deviceLinked":
      return a.deviceLinked.toString().localeCompare(b.deviceLinked.toString())

    case "startsWith":
      return a?.startsWith?.localeCompare(b?.startsWith)

    case "imei":
      return a?.imei?.localeCompare(b?.imei)

    case "status":
      return a.status.localeCompare(b.status)

    default:
      return 0
  }
}
/**
 * Mock “server” list: filter → sort → paginate over {@link mockFactoryList}.
 * Replace with a real `fetch()` when an API exists; keep the same result shape.
 */
export function queryFactoryOverviewPage(query: FactoryOverviewQuery): CabinetsListPageResult {
  const filtered = filterFactoryRows(
    query.data,
    query.search,
    query.prefix,
    query.linked,
    query?.dateRange
  )

  const sorted = [...filtered]
  const sort = query.sorting[0]
  if (sort) {
    sorted.sort((a, b) => {
      const cmp = compareRows(a, b, sort.id)
      return sort.desc ? -cmp : cmp
    })
  }

  const totalCount = sorted.length
  const start = query.pageIndex * query.pageSize
  const rows = sorted.slice(start, start + query.pageSize)

  return { rows, totalCount }
}
