/**
 * Generated by AI, to be replaced with a real API call later.
 * Mock server-side list filtering and sorting for cabinets list.
 */
import type { FactoryRow } from "../types/factoryType"

export type FactoryImeiLinkingQuery = {
  search: string
  pageIndex: number
  pageSize: number
  combination: string
  data: FactoryRow[]
}

export type CabinetsListPageResult = {
  rows: FactoryRow[]
  totalCount: number
}

function filterFactoryRows(
  rows: readonly FactoryRow[],
  search: string,
  combination: string
): FactoryRow[] {
  const q = search.trim().toLowerCase()

  return rows.filter((row) => {
    const matchesSearch =
      !q ||
      row.nexCode?.toLowerCase().includes(q) ||
      row.updCode?.toLowerCase().includes(q) ||
      row.combination?.toLowerCase().includes(q) ||
      row.imei?.toLowerCase().includes(q) ||
      row.moduleModel?.toLowerCase().includes(q)

    const matchesCombination =
      !combination ||
      combination === "all" ||
      row.combination === combination

    return matchesSearch && matchesCombination
  })
}
/**
 * Mock “server” list: filter → sort → paginate over {@link mockFactoryList}.
 * Replace with a real `fetch()` when an API exists; keep the same result shape.
 */
export function queryImeiLinkingPage(query: FactoryImeiLinkingQuery): CabinetsListPageResult {
  const filtered = filterFactoryRows(
    query.data,
    query.search,
    query.combination,
  )

  const totalCount = filtered.length
  const start = query.pageIndex * query.pageSize
  const rows = filtered.slice(start, start + query.pageSize)

  return { rows, totalCount }
}
