/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { formatISODate } from "@/lib/utils"
import type { AvailableSerialNumbersRow } from "../types/factoryType"
const columnHelper = createColumnHelper<AvailableSerialNumbersRow>()

export const availableSerialColumn = () => [
  columnHelper.accessor("serialNumber", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Serial Number" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.serialNumber,
  }),

  columnHelper.accessor("type", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Type" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.type,
  }),

  columnHelper.accessor("deviceModel", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Module model" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => row.original?.deviceModel?.modelName || "—",
  }),

  columnHelper.accessor("generatedAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Generated at" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => formatISODate(row.original.generatedAt),
  }),

]