/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { formatISODate } from "@/lib/utils"
import type { FactoryRow } from "../types/factoryType"
const columnHelper = createColumnHelper<FactoryRow>()

export const availableSerialColumn = () => [
  columnHelper.accessor("serialNumber", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Serial Number" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.serialNumber,
  }),

  columnHelper.accessor("type", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Type" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle whitespace-nowrap",
    },
    // cell: ({ row }) => row.original.prefix,
    cell: ({ }) => "NEX",
  }),

  columnHelper.accessor("model", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Module model" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => row.original.model || "V1",
  }),

  columnHelper.accessor("createdAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Generated On" />
    ),
    meta: {
      headerClassName: "xl:w-1/4",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => formatISODate(row.original.createdAt),
  }),

]