/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { cn, formatISODate } from "@/lib/utils"
import type { FactoryRow } from "../types/factoryType"
import UnCheckIcon from "@/assets/icons/unlinked.svg?react"
import CheckIcon from "@/assets/icons/check.svg?react"

const columnHelper = createColumnHelper<FactoryRow>()

export const factoryOverviewColumns = () => [
  columnHelper.accessor("serialNumber", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Serial Number" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.serialNumber,
  }),

  columnHelper.accessor("id", { // accessor is set id cause prefix is static - NEX
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Prefix" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    // cell: ({ row }) => row.original.prefix,
    cell: ({ }) => "NEX",
  }),

  columnHelper.accessor("createdAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Generated On" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => formatISODate(row.original.createdAt),
  }),


  columnHelper.accessor("deviceLinked", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Linked Status" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => (
      <span className="flex items-center gap-1 capitalize">
        <span className={cn("flex gap-1.5")}>
          {row.original.deviceLinked ? <>
            <CheckIcon className="size-4 text-success2" />
            Linked
          </> : <>
            <UnCheckIcon />
            Unlinked
          </>}
        </span>
      </span>
    ),
  }),

  columnHelper.accessor("imei", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="IMEI Number" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.imei,
  }),

]