/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { formatISODate } from "@/lib/utils"
import type { FactoryRow } from "../types/factoryType"

const columnHelper = createColumnHelper<FactoryRow>()

export const linkedCombinationColumns = () => [
  columnHelper.accessor("combination", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Combination" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.combination,
  }),

  columnHelper.accessor("nexCode", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="NEX code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.nexCode || "—",
  }),

  columnHelper.accessor("updCode", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="UPD code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.updCode || "—",
  }),

  columnHelper.accessor("imei", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="IMEI" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.imei || "—",
  }),

  columnHelper.accessor("moduleModel", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Module model" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => row.original.moduleModel || "—",
  }),

  columnHelper.accessor("scannedAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Scanned at" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => formatISODate(row.original.scannedAt),
  }),

]