/**
 * Columns for the cabinets list table.
 * Partially generated by AI, to be replaced with a real API call later.
 */
import { createColumnHelper } from "@tanstack/react-table"
import { DataTableColumnHeader } from "@/shared/components/data-table"
import { formatDateTime } from "@/lib/utils"
import type { FactoryRow } from "../types/factoryType"

const columnHelper = createColumnHelper<FactoryRow>()

export const linkedCombinationColumns = () => [
  columnHelper.accessor("combination", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Combination" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.serialNumber,
  }),

  columnHelper.accessor("nexCode", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="NEX code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    // cell: ({ row }) => row.original.nexCode,
    cell: ({ }) => "NEX26-0001-0042",
  }),

  columnHelper.accessor("updCode", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="UPD code" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    // cell: ({ row }) => "UPD26-0001-0183",
    cell: ({ }) => "UPD26-0001-0183",
  }),

  columnHelper.accessor("imei", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="IMEI" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle whitespace-nowrap",
    },
    cell: ({ row }) => row.original.imei || "—",
  }),

  columnHelper.accessor("model", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Module model" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => row.original.model || "V1",
  }),

  columnHelper.accessor("linkedAt", {
    header: ({ column }) => (
      <DataTableColumnHeader column={column} title="Processed at" />
    ),
    meta: {
      headerClassName: "",
      cellClassName: "align-middle",
    },
    cell: ({ row }) => formatDateTime(row.original.createdAt),
  }),

]